### ISSUE TITLE
angular-cli-hooks fresh installs fail during postinstall

### ISSUE THREAD

**Issue by wjaspers** [blidblid/berglund#9]
### environment

```
node v16.14.0
npm 8.15.1
angular 14
```

### package.json
```
...
dependencies: {
...
"@berglund/angular-cli-hooks": "^0.0.8"
...
}
...
```

### install
```
$ npm i
npm ERR! code 1

npm ERR! path /home/wjaspers/project/node_modules/@berglund/angular-cli-hooks
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-acebd845.sh
npm ERR! node:internal/fs/utils:344
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: ENOENT: no such file or directory, open '/home/wjaspers/project/node_modules/@berglund/angular-cli-hooks/src/builders/browser-esbuild/schema.json'
npm ERR!     at Object.openSync (node:fs:585:3)
npm ERR!     at writeFileSync (node:fs:2155:35)
npm ERR!     at generateSchemaJson (/home/wjaspers/project/node_modules/@berglund/angular-cli-hooks/scripts/postinstall.js:28:32)
npm ERR!     at generate (/home/wjaspers/project/node_modules/@berglund/angular-cli-hooks/scripts/postinstall.js:11:5)
npm ERR!     at Object.<anonymous> (/home/wjaspers/project/node_modules/@berglund/angular-cli-hooks/scripts/postinstall.js:12:3)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1103:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
npm ERR!   errno: -2,
npm ERR!   syscall: 'open',
npm ERR!   code: 'ENOENT',
npm ERR!   path: '/home/wjaspers/project/node_modules/@berglund/angular-cli-hooks/src/builders/browser-esbuild/schema.json'
npm ERR! }
```

### workaround

```
npm i --ignore-scripts && npm i
```

**Comment by fidian** [comment]
The workaround doesn't work for me. When I try to run a build, it fails with a schema error. However, this command seems to be a working workaround.

```
npm ci --ignore-scripts && (cd node_modules/\@berglund/angular-cli-hooks; cp -r src/builders/{browser,browser-esbuild}; npm run postinstall)
```

**Comment by blidblid** [comment]
Can you try version 0.0.9? Should be fixed.

**Comment by fidian** [comment]
Works for me. Thank you very much!
